### ISSUE TITLE
No available formula with the name "gcc@6"

### ISSUE THREAD

**Issue by tepsl** [cosmo0920/homebrew-mingw_w64#14]
brew upgrade fails with the error message;

> Error: No available formula with the name "gcc@6" (dependency of cosmo0920/mingw_w64/i686-w64-mingw32-binutils)

It might be related to the closed issue #13

**Comment by cosmo0920** [comment]
Thanks for the report.
`gcc@6` had been disappeared in this commit: https://github.com/Homebrew/homebrew-core/commit/e0fe04baa81a06327a3bca9ead62b3743f8683a0

I'll fix it soon.

**Comment by cosmo0920** [comment]
I've changed dependency to use `gcc` instead of `gcc@6`.
Could you try to upgrade again?

**Comment by tepsl** [comment]
It worked!
Thanks.
