### ISSUE TITLE
conflicting version recursive dependencies

### ISSUE THREAD

**Issue by digiola** [cosmo0920/homebrew-mingw_w64#16]
I've been using your Homebrew i686-w64-mingw32-gcc for over 2 years and have a tutorial on the [Magic Lantern forum](http://www.magiclantern.fm/forum/index.php?topic=16012.0) that shows how to install it. A user contacted me with this issue and I was able to reproduce it on a new Homebrew install:

`brew install cosmo0920/mingw_w64/i686-w64-mingw32-gcc

==> Tapping cosmo0920/mingw_w64
Cloning into '/usr/local/Homebrew/Library/Taps/cosmo0920/homebrew-mingw_w64'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 2), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), done.
Tapped 4 formulae (39 files, 55.0KB)
==> Installing i686-w64-mingw32-gcc from cosmo0920/mingw_w64
Error: cosmo0920/mingw_w64/i686-w64-mingw32-gcc contains conflicting version recursive dependencies:
  isl, isl@0.14
View these with `brew deps --tree cosmo0920/mingw_w64/i686-w64-mingw32-gcc`.`

**Comment by cosmo0920** [comment]
Thanks for your report!
But recently homebrew-core got merged [mingw-64](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mingw-w64.rb) Formula which installs cross gcc and binutils at once.

Could you tell users to use mingw-w64 instead of my formula?

**Comment by digiola** [comment]
Thanks, I didn't know. Just tried it and it works great.
