### ISSUE TITLE
Formulae violates path rules when users does not instal in `/usr/local`

### ISSUE THREAD

**Issue by cosmo0920** [cosmo0920/homebrew-mingw_w64#4]
Formulae should use `prefix+"/mingw"` instead of hand written path(`/usr/local/mingw`).
This violation causes trouble when users install Homebrew in unordinary prefix.

**Comment by mbudisic** [comment]
On my machine, homebrew repeatedly tries to install to "/mingw" (that is, subdirectory of root, not /usr/local or /usr/local/Cellar). I have nothing special about my homebrew installation, but please let me know what information I can provide to help resolve this.

Thanks for your formula - I'd find it very useful once I get it running.

**Comment by cosmo0920** [comment]
Ah, my fix is wrong.
Thanks for the report.
I'll fix it.

**Comment by cosmo0920** [comment]
I committed to fix problem https://github.com/cosmo0920/homebrew-mingw_w64/commit/067cc50305423e84a335d9fab330efc86031f273.

This revision also causes problems?

**Comment by cosmo0920** [comment]
binutils-mingw32.rb installation succeeded in my environment.
I close this issue.

@mbudisic If there is still any problem, please let me know.

**Comment by mbudisic** [comment]
This fixes it, thanks for the quick attention to this issue (and for the great formula).

**Comment by cosmo0920** [comment]
Thanks for confirming it!

> (and for the great formula)

I'm glad to hear that!!! :)
