### ISSUE TITLE
Error when installing binutils

### ISSUE THREAD

**Issue by dreambottle** [cosmo0920/homebrew-mingw_w64#6]
Hi! I can't install mingw (neither 64 nor 32) with this formula because I get the following error while trying to install binutils:

```
==> Installing binutils-mingw32 from cosmo0920/mingw_w64
==> Downloading http://ftpmirror.gnu.org/binutils/binutils-2.25.1.tar.bz2
==> Downloading from http://ftp-gnu-org.ip-connect.vn.ua/binutils/binutils-2.25.1.tar.bz2
######################################################################## 100.0%
==> ./configure CC=gcc-4.9 CXX=g++-4.9 CPP=cpp-4.9 LD=gcc-4.9 --target=i686-w64-mingw32 --disable-
==> make
==> make install-strip
Error: Empty installation
```

Do you have any ideas about the reason of this error?

**Comment by cosmo0920** [comment]
Thanks for the report.
This issue may be caused by this Homebrew commit: https://github.com/Homebrew/homebrew/commit/915ac06db21acc5c9595b2223cc39b9672f34c4a.

Related to #1.

**Comment by cosmo0920** [comment]
This phenomenon is caused by using non-standard install prefix: https://github.com/cosmo0920/homebrew-mingw_w64/blob/master/binutils-mingw32.rb#L11

We should use `prefix` in ./configure option. 
But for now, I didn't find suitable way to adopt mingw64 toolchain cross compilation for this validation.

**Comment by cosmo0920** [comment]
I added a workaround against empty installation error: https://github.com/cosmo0920/homebrew-mingw_w64/commit/8c0baeeb78cddede8e4c3d850e8c8f96700d9d10

Could you try update and install again?

**Comment by dreambottle** [comment]
Thanks! Installs just fine now

**Comment by cosmo0920** [comment]
I'm glad to hear that. Thanks for confirming it! 😊
