### ISSUE TITLE
Resolve symlinking conflict and remove keg_only 

### ISSUE THREAD

**Issue by cosmo0920** [cosmo0920/homebrew-mingw_w64#8]
See: https://github.com/cosmo0920/homebrew-mingw_w64/issues/1#issuecomment-173895506

**Comment by FiloSottile** [comment]
It should be just a matter of moving all the installation to libexec, and then symlink just the binaries. Like I did in https://github.com/FiloSottile/homebrew-musl-cross/blob/1b5a7a2fe85cd306b7d5d6683e98d0be22aa7e72/musl-cross.rb#L108

No need to actually clear the conflict.

**Comment by FiloSottile** [comment]
(By the way, thanks for the formulae, they saved me loads of time!)

**Comment by cosmo0920** [comment]
It sounds interesting to me! 
Thanks for telling the great information. :laughing:
